[2024-12-10T07:42:21.969+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-10T07:42:22.083+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.load_weather_data scheduled__2024-12-09T00:00:00+00:00 [queued]>
[2024-12-10T07:42:22.142+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.load_weather_data scheduled__2024-12-09T00:00:00+00:00 [queued]>
[2024-12-10T07:42:22.170+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-10T07:42:22.257+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_weather_data> on 2024-12-09 00:00:00+00:00
[2024-12-10T07:42:22.283+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2736) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-10T07:42:22.288+0000] {standard_task_runner.py:72} INFO - Started process 2738 to run task
[2024-12-10T07:42:22.286+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'load_weather_data', 'scheduled__2024-12-09T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/portland_weather_data_pipeline.py', '--cfg-path', '/tmp/tmpmji9flaf']
[2024-12-10T07:42:22.300+0000] {standard_task_runner.py:105} INFO - Job 103: Subtask load_weather_data
[2024-12-10T07:42:22.513+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.load_weather_data scheduled__2024-12-09T00:00:00+00:00 [running]> on host 4ccd8b9315ad
[2024-12-10T07:42:23.899+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-09T00:00:00+00:00'
[2024-12-10T07:42:23.929+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-10T07:42:23.992+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-10T07:42:24.020+0000] {logging_mixin.py:190} INFO - Current task name:load_weather_data state:running start_date:2024-12-10 07:42:22.097022+00:00
[2024-12-10T07:42:24.035+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_pipeline and current dag run status:running
[2024-12-10T07:42:24.038+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-10T07:42:24.089+0000] {base.py:84} INFO - Retrieving connection 'portland_data'
[2024-12-10T07:42:31.461+0000] {logging_mixin.py:190} INFO - Error while connecting to PostgreSQL or executing the query: could not translate host name "***" to address: Name or service not known
[2024-12-10T07:42:31.463+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/portland_weather_data_pipeline.py", line 277, in load_data_to_postgres
    if cursor:
       ^^^^^^
UnboundLocalError: cannot access local variable 'cursor' where it is not associated with a value
[2024-12-10T07:42:31.563+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-10T07:42:31.571+0000] {logging_mixin.py:190} INFO - Task start:2024-12-10 07:42:22.097022+00:00 end:2024-12-10 07:42:31.562445+00:00 duration:9.465423
[2024-12-10T07:42:31.579+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_weather_data> dag:<DAG: weather_data_pipeline> dagrun:<DagRun weather_data_pipeline @ 2024-12-09 00:00:00+00:00: scheduled__2024-12-09T00:00:00+00:00, state:running, queued_at: 2024-12-10 00:23:42.697892+00:00. externally triggered: False>
[2024-12-10T07:42:31.583+0000] {logging_mixin.py:190} INFO - Failure caused by cannot access local variable 'cursor' where it is not associated with a value
[2024-12-10T07:42:31.592+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_pipeline, task_id=load_weather_data, run_id=scheduled__2024-12-09T00:00:00+00:00, execution_date=20241209T000000, start_date=20241210T074222, end_date=20241210T074231
[2024-12-10T07:42:31.705+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-10T07:42:31.708+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 103 for task load_weather_data (cannot access local variable 'cursor' where it is not associated with a value; 2738)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/portland_weather_data_pipeline.py", line 277, in load_data_to_postgres
    if cursor:
       ^^^^^^
UnboundLocalError: cannot access local variable 'cursor' where it is not associated with a value
[2024-12-10T07:42:31.819+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-10T07:42:31.921+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-10T07:42:31.945+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
